export enum RegisterType{
    REGISTER_START='[REGISTER] REGISTER START',
    REGISTER_SUCCESS='[REGISTER] REGISTER SUCCESS',
    REGISTER_ERROR='[REGISTER] REGISTER ERROR',
}

export enum ProfileType{
    PROFILE_START='[PROFILE] PROFILE START',
    PROFILE_SUCCESS='[PROFILE] PROFILE SUCCESS',
    PROFILE_ERROR='[PROFILE] PROFILE ERROR',
}

export enum ManagerType{
    MANAGER_START='[MANAGER] MANAGER START',
    MANAGER_SUCCESS='[MANAGER] MANAGER SUCCESS',
    MANAGER_ERROR='[MANAGER] MANAGER ERROR',
}

export enum StudentsType{
    STUDENTS_START='[STUDENTS] STUDENTS START',
    STUDENTS_SUCCESS='[STUDENTS] STUDENTS SUCCESS',
    STUDENTS_ERROR='[STUDENTS] STUDENTS ERROR',
}

export enum TeachersType{
    TEACHERS_START='[TEACHERS] TEACHERS START',
    TEACHERS_SUCCESS='[TEACHERS] TEACHERS SUCCESS',
    TEACHERS_ERROR='[TEACHERS] TEACHERS ERROR',
}

export enum AllCourseType{
    ALL_COUESE_START='[ALL_COUESE] ALL_COUESE START',
    ALL_COUESE_SUCCESS='[ALL_COUESE] ALL_COUESE SUCCESS',
    ALL_COUESE_ERROR='[ALL_COUESE] ALL_COUESE ERROR',
}

export enum ModuleByCourseId{
    MODULEBYCOURSEID_START='[MODULEBYCOURSEID] MODULEBYCOURSEID START',
    MODULEBYCOURSEID_SUCCESS='[MODULEBYCOURSEID] MODULEBYCOURSEID SUCCESS',
    MODULEBYCOURSEID_ERROR='[MODULEBYCOURSEID] MODULEBYCOURSEID ERROR',
}

export enum CreateCourse{
    CREATECOURSE_START='[CREATECOURSE] CREATECOURSE START',
    CREATECOURSE_SUCCESS='[CREATECOURSE] CREATECOURSE SUCCESS',
    CREATECOURSE_ERROR='[CREATECOURSE] CREATECOURSE ERROR',
}

export enum CreateGroupe{
    CREATEGROUP_START='[CREATEGROUP] CREATEGROUP START',
    CREATEGROUP_SUCCESS='[CREATEGROUP] CREATEGROUP SUCCESS',
    CREATEGROUP_ERROR='[CREATEGROUP] CREATEGROUP ERROR',
}

export enum CreateModule{
    CREATEMODULE_START='[CREATEMODULE] CREATEMODULE START',
    CREATEMODULE_SUCCESS='[CREATEMODULE] CREATEMODULE SUCCESS',
    CREATEMODULE_ERROR='[CREATEMODULE] CREATEMODULE ERROR',
}

export enum UpdateCourse{
    UPDATECOURSE_START='[UPDATECOURSE] UPDATECOURSE START',
    UPDATECOURSE_SUCCESS='[UPDATECOURSE] UPDATECOURSE SUCCESS',
    UPDATECOURSE_ERROR='[UPDATECOURSE] UPDATECOURSE ERROR',
}

export enum AllGroups{
    ALLGROUPS_START='[ALLGROUPS] ALLGROUPS START',
    ALLGROUPS_SUCCESS='[ALLGROUPS] ALLGROUPS SUCCESS',
    ALLGROUPS_ERROR='[ALLGROUPS] ALLGROUPS ERROR',
}

export enum UpdateModuleNameAndCount{
    UPDATEMODULENAMEANDCOUNT_START='[UPDATEMODULENAMEANDCOUNT] UPDATEMODULENAMEANDCOUNT START',
    UPDATEMODULENAMEANDCOUNT_SUCCESS='[UPDATEMODULENAMEANDCOUNT] UPDATEMODULENAMEANDCOUNT SUCCESS',
    UPDATEMODULENAMEANDCOUNT_ERROR='[UPDATEMODULENAMEANDCOUNT] UPDATEMODULENAMEANDCOUNT ERROR',
}