export enum RegisterType{
    REGISTER_START='[REGISTER] REGISTER START',
    REGISTER_SUCCESS='[REGISTER] REGISTER SUCCESS',
    REGISTER_ERROR='[REGISTER] REGISTER ERROR',
}

export enum ProfileType{
    PROFILE_START='[PROFILE] PROFILE START',
    PROFILE_SUCCESS='[PROFILE] PROFILE SUCCESS',
    PROFILE_ERROR='[PROFILE] PROFILE ERROR',
}

export enum ManagerType{
    MANAGER_START='[MANAGER] MANAGER START',
    MANAGER_SUCCESS='[MANAGER] MANAGER SUCCESS',
    MANAGER_ERROR='[MANAGER] MANAGER ERROR',
}

export enum StudentsType{
    STUDENTS_START='[STUDENTS] STUDENTS START',
    STUDENTS_SUCCESS='[STUDENTS] STUDENTS SUCCESS',
    STUDENTS_ERROR='[STUDENTS] STUDENTS ERROR',
}

export enum TeachersType{
    TEACHERS_START='[TEACHERS] TEACHERS START',
    TEACHERS_SUCCESS='[TEACHERS] TEACHERS SUCCESS',
    TEACHERS_ERROR='[TEACHERS] TEACHERS ERROR',
}